### ISSUE TITLE
Create UI for receive coins

### ISSUE THREAD

**Issue by daxicek** [SimplioOfficial/simplio-app#117]
# Overview

Create UI for receiving all coins and tokens with QR code based on UX design

## Requirements

- Show QR code and address of Bitcoin
- Show copy button + copy on click on address

**Comment by MariooW** [comment]
Need to be discussed. at this moment on activate this feature my FLASH blinking. On copy there is no an info that the content of QR code was copied. After scan camera was off and feature still shows running line....why cannot we all user to rescan QR code once again without turning of this function.
