### ISSUE TITLE
Separate view layer extensions

### ISSUE THREAD

**Issue by storkandstars** [SimplioOfficial/simplio-app#203]
# Overview

Keep view layer extensions separated from other layers

https://github.com/SimplioOfficial/simplio-app/blob/a85c8e187a26c8f2bf06975e629431ecbd727d87/lib/extensions/date_extensions.dart#L3

**Comment by TomasPetrik** [comment]
@storkandstars 
I already moved it into view/extensions folder in some commit before. This change is already in master.

**Comment by TomasPetrik** [comment]
@MariooW 
This one you are not able to test as it's only code change what has not impact on any visible part.
