### ISSUE TITLE
Wrong Icons in UI

### ISSUE THREAD

**Issue by MariooW** [SimplioOfficial/simplio-app#240]
**Description:**

IN Discover part and also in some other places icons are not consistent with FIGMA DESIGNS. 

**How to reproduce:**

1. open app 
2. login 
3. check icons

**Actual:**
Some applications are different than designed

**Expected:**
Icons will be in consistency with design

![Image](https://user-images.githubusercontent.com/87430514/193431221-c9eadf5a-4c25-4629-b202-822aca7eb2ae.png)

**Comment by satyamnoob** [comment]
May you assign this to me?

**Comment by daxicek** [comment]
It´s because #244 is still not done. Closing for now.
