### ISSUE TITLE
Missing an info when any game was found

### ISSUE THREAD

**Issue by MariooW** [SimplioOfficial/simplio-app#241]
**Description:**
When game was not found and list is empty (it will happened when search field will be empty) is missing an info to let user name that he will need to start typing. It can be not clear for users and can confuse them. 

**How to reproduce:**

1. open app
2. login
3. go to DISCOVER
4. click in search field in GAMES

**Actual:**
Nothing appear. There is no info that the user have to start typing to see anything.

**Expected:**
Need to be discussed with management/ UX designer

![Image](https://user-images.githubusercontent.com/87430514/193431384-91390f1e-3d35-47d8-93e1-e0d5371fe51a.jpg)

**Comment by daxicek** [comment]
This is correct behavior. Closing.
