### ISSUE TITLE
Interrupting login process left on put pin after reset app

### ISSUE THREAD

**Issue by MariooW** [SimplioOfficial/simplio-app#253]
**Description:**
When user will interrupt login on PUT PIN and he will left an app then on run it he will be redirected to put this PIN. In this case someone can take his phone and go to the app by put his own PIN code.

**How to reproduce:**

- open 

1. open app 
2. put email and password
3. go to the PUT pin
4. go out from the app
5. ope app again

**Actual:**
The user will be moved to the SET PIN page

**Expected:**
In my opinion from security point of view is not good behavior.

https://user-images.githubusercontent.com/87430514/194813480-627663bd-190f-43e4-9aa5-7796fd2dc90b.mp4

**Comment by storkandstars** [comment]
It is expected behaviour. We will analyse the security risk and make possible changes.
