### ISSUE TITLE
Missing coin icon in coin details

### ISSUE THREAD

**Issue by MariooW** [SimplioOfficial/simplio-app#268]
**Description:**
In coin details there is no proper icon. Icons for coins are visible on the list of coins in inventory page

**How to reproduce:**

1. open app
2. login
3. go to inventory
4. add coin
5. go to coin details

**Actual:**
There is no ICON on the top of page.

**Expected:**
Coin icon will be visible everywhere it is.

![Image](https://user-images.githubusercontent.com/87430514/196106347-a2a4d93f-29c4-4cae-b311-4244b7c893d0.png)

**Comment by TomasPetrik** [comment]
It's fixed in https://github.com/SimplioOfficial/simplio-app/pull/270

task/244-simplio-glyphs
