### ISSUE TITLE
Change to synced api calls in exchange

### ISSUE THREAD

**Issue by ciripel** [SimplioOfficial/simplio-app#295]
When you start typing the numbers in any of Amount from/to fields in Exchange screen there is the possibility that the previous fetch amount api call will arrive after the last call and the value in the other field will be wrong.

A synchronous api calls stream must be implemented to take the calls in the order that they were sent.

**Comment by ciripel** [comment]
I think the same must be applied to buy cubit

**Comment by daxicek** [comment]
@storkandstars already working on this. duplication, closing
