### ISSUE TITLE
expansion list keeps unresponsive when wallet is disabled

### ISSUE THREAD

**Issue by storkandstars** [SimplioOfficial/simplio-app#323]
# Overview

Go to a asset wallet detail screen. Click on remove from inventory. Go back to inventory. The removed wallet should not be there. Try to add it again through search. The wallet was added in opened state (expansion widget) and cannot be closed.

**Comment by jvrastil** [comment]
it's partially working. @daxicek need to specify correct expansion list behavior before further work

**Comment by daxicek** [comment]
@jvrastil yes correct, once you want to add it again it should be same like adding new wallet so NOT expanded list
