### ISSUE TITLE
enabled wallets are not filtered across app

### ISSUE THREAD

**Issue by storkandstars** [SimplioOfficial/simplio-app#361]
# Overview

If a wallet is disabled (removed from inventory), it is not showed in inventory anymore. However it can be selected in swap screen and similar ones. 

# Requirements

- filter enabled wallets on cubit state level in a getter. not on screen level.

**Comment by daxicek** [comment]
@jvrastil attaching video and returning to backlog.



https://user-images.githubusercontent.com/573455/202482449-16b1f9eb-83cc-438a-a9d7-642a785a3e49.mp4
