### ISSUE TITLE
refactor dialog displays

### ISSUE THREAD

**Issue by storkandstars** [SimplioOfficial/simplio-app#471]
# Overview

display dialogs using built-in bottom modal sheets in Flutter. Make dialogs a widgets with functionalities that live inside `view/dialog` folder.

**Comment by TomasPetrik** [comment]
1. Bottom sheet dialogs are using `showModalBottomSheet` method to be shown,
2. Popup dialogs are using `showPopup` and `showErrorPopup` methods to be shown.
3. Moved all dialogs into view/dialog folder,
4. Merged regular and error popup dialogs into one class,
5. Added 'dialog' in the end of file name,
6. Fixed also not appearing popup dialog after big refactor.
